In [39]:
import pandas as pd
import numpy as np

In [ ]:
# load the dfs
one = pd.read_csv('data/wiki_daily_views_all.csv', parse_dates=['date'], index_col='date')
two = pd.read_csv('data/wiki_extras.csv', parse_dates=['date'], index_col='date')

# joining the dfs
merged = one.join(two, how='outer', lsuffix='_all', rsuffix='_manual')

# sort by date
merged = merged.sort_index()

# rename cols and save
merged = merged.rename(columns={'Steemit': 'STEEM', '0x_(decentralized_exchange_infrastructure)': 'ZRX', 'ICON_(blockchain_platform)': 'ICX'})
merged.to_csv('data/wiki_dv.csv')

In [41]:
merged.head()

,BTC,XRP,BNB,DOGE,ADA,TRX,LTC,LINK,BCH,EOS,...,SYS,REQ,FUN,VIB,IDEX,MDT,BORG,STEEM,ZRX,ICX
date,,,,,,,,,,,,,,,,,,,,,
2018-01-01,23,76,0.0,0.0,0.0,33.0,12,0.0,27.0,5.0,...,9.0,0.0,5.0,5.0,2.0,15,0.0,837,0.0,0.0
2018-01-02,40,144,0.0,0.0,0.0,48.0,22,0.0,23.0,11.0,...,5.0,0.0,3.0,5.0,4.0,22,0.0,1619,0.0,0.0
2018-01-03,44,178,0.0,0.0,0.0,51.0,18,0.0,29.0,12.0,...,9.0,0.0,4.0,3.0,10.0,29,0.0,1708,0.0,0.0
2018-01-04,65,196,0.0,5.0,0.0,90.0,18,0.0,26.0,11.0,...,8.0,0.0,11.0,2.0,3.0,28,0.0,1709,0.0,0.0
2018-01-05,78,176,0.0,4.0,0.0,81.0,20,1.0,15.0,15.0,...,7.0,0.0,1.0,10.0,2.0,20,0.0,1576,0.0,0.0

In [42]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2557 entries, 2018-01-01 to 2024-12-31
Data columns (total 76 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   BTC     2557 non-null   int64
 1   XRP     2557 non-null   int64
 2   BNB     2557 non-null   float64
 3   DOGE    2557 non-null   float64
 4   ADA     2557 non-null   float64
 5   TRX     2557 non-null   float64
 6   LTC     2557 non-null   int64
 7   LINK    2557 non-null   float64
 8   BCH     2557 non-null   float64
 9   EOS     2557 non-null   float64
 10  ETC     2557 non-null   int64
 11  MKR     2557 non-null   float64
 12  ZEC     2557 non-null   float64
 13  XLM     2557 non-null   float64
 14  XMR     2557 non-null   float64
 15  MANA    2557 non-null   float64
 16  DASH    2557 non-null   float64
 17  NEO     2557 non-null   float64
 18  ELF     2557 non-null   int64
 19  SNX     2557 non-null   float64
 20  STORJ   2557 non-null   float64
 21  VGX     2557 non-null   float64
 22  ENJ     2557 non-null   float64
 23  DGB     2557 non-null   float64
 24  ZEN     2557 non-null   float64
 25  GLM     2557 non-null   float64
 26  ZIL     2557 non-null   float64
 27  BAT     2557 non-null   int64
 28  GFT     2557 non-null   float64
 29  GNO     2557 non-null   float64
 30  IOTA    2557 non-null   float64
 31  MED     2557 non-null   float64
 32  LRC     2557 non-null   float64
 33  POWR    2557 non-null   float64
 34  AMB     2557 non-null   int64
 35  WAVES   2557 non-null   int64
 36  CVC     2557 non-null   int64
 37  RVN     2557 non-null   float64
 38  ONT     2557 non-null   int64
 39  REN     2557 non-null   float64
 40  XDC     2557 non-null   float64
 41  DENT    2557 non-null   float64
 42  ARK     2557 non-null   float64
 43  BLZ     2557 non-null   float64
 44  GAS     2557 non-null   float64
 45  NMR     2557 non-null   int64
 46  ANT     2557 non-null   float64
 47  OMG     2557 non-null   int64
 48  ADX     2557 non-null   int64
 49  RLC     2557 non-null   float64
 50  VIC     2557 non-null   float64
 51  LSK     2557 non-null   int64
 52  SBD     2557 non-null   int64
 53  ARDR    2557 non-null   float64
 54  TRAC    2557 non-null   float64
 55  PRO     2557 non-null   float64
 56  BTG     2557 non-null   float64
 57  MLN     2557 non-null   float64
 58  XVG     2557 non-null   float64
 59  XNO     2557 non-null   float64
 60  MTL     2557 non-null   int64
 61  UQC     2557 non-null   float64
 62  DCR     2557 non-null   int64
 63  SNT     2557 non-null   float64
 64  UTK     2557 non-null   float64
 65  PIVX    2557 non-null   float64
 66  SYS     2557 non-null   float64
 67  REQ     2557 non-null   float64
 68  FUN     2557 non-null   float64
 69  VIB     2557 non-null   float64
 70  IDEX    2557 non-null   float64
 71  MDT     2557 non-null   int64
 72  BORG    2557 non-null   float64
 73  STEEM   2557 non-null   int64
 74  ZRX     2557 non-null   float64
 75  ICX     2557 non-null   float64
dtypes: float64(57), int64(19)
memory usage: 1.5 MB

In [ ]:
df = pd.read_csv('data/wiki_dv.csv')

df['date'] = pd.to_datetime(df['date'])
df = df.set_index('date').sort_index()

# compute daily % change, clean up infs, drop rows where every coin is NaN
daily_change = df.pct_change()
daily_change = daily_change.replace([np.inf, -np.inf], np.nan).dropna(how='all')

daily_change.to_csv('data/wiki_daily_pct_change.csv')